'use client';

import React, { useState, useEffect } from 'react';
import { useMutation } from '@tanstack/react-query';
import { api } from '@/utils/api';
import { useToastStore } from '@/hooks/useToastStore';
import { Loader2, CheckCircle2, ArrowLeft, KeyRound, BookOpen } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

export default function StudentCheckInPage() {
  const router = useRouter();
  const { addToast } = useToastStore();
  const [code, setCode] = useState('');
  const [successData, setSuccessData] = useState<any>(null);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const urlParams = new URLSearchParams(window.location.search);
      const queryCode = urlParams.get('code');
      if (queryCode) {
        setCode(queryCode.toUpperCase());
      }
    }
  }, []);

  const checkInMutation = useMutation({
    mutationFn: async (checkInCode: string) => {
      const response = await api.post('/courses/attendance/checkin', { code: checkInCode });
      return response.data;
    },
    onSuccess: (data) => {
      setSuccessData(data);
      addToast(data.message, 'success');
    },
    onError: (err: any) => {
      addToast(err.response?.data?.message || 'Failed to submit check-in code', 'error');
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!code.trim()) {
      return addToast('Please enter an attendance code', 'error');
    }
    checkInMutation.mutate(code.trim().toUpperCase());
  };

  return (
    <div className="space-y-6 max-w-md mx-auto animate-fade-in pt-8">
      
      {/* Header back link */}
      <div className="flex items-center gap-3">
        <Link
          href="/dashboard/student"
          className="p-2.5 bg-beige-200 text-text-secondary hover:text-text-primary rounded-xl transition-all"
        >
          <ArrowLeft className="w-4 h-4" />
        </Link>
        <div>
          <h2 className="text-xl font-bold text-text-primary">Attendance Check-in</h2>
          <p className="text-xs text-text-secondary">Self check-in to your active course lectures.</p>
        </div>
      </div>

      <div className="bg-white p-6 md:p-8 rounded-3xl border border-beige-200/80 shadow-premium">
        {!successData ? (
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="w-12 h-12 bg-mint-50 rounded-2xl flex items-center justify-center text-mint-500 mx-auto">
              <KeyRound className="w-6 h-6" />
            </div>

            <div className="text-center space-y-1.5">
              <h3 className="text-sm font-bold text-text-primary">Enter Check-in Code</h3>
              <p className="text-[10px] text-text-secondary leading-normal max-w-xs mx-auto">
                Type the 6-character check-in code generated by your instructor or Teaching Assistant.
              </p>
            </div>

            <div className="space-y-1.5">
              <input
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value.toUpperCase())}
                placeholder="e.g. E5F3W9"
                className="w-full text-center px-4 py-3 bg-beige-50/50 border border-beige-200 rounded-xl text-lg font-black tracking-widest text-text-primary focus:border-mint-500 outline-none transition-all uppercase placeholder:normal-case placeholder:font-semibold placeholder:text-xs placeholder:tracking-normal"
                maxLength={6}
                required
              />
            </div>

            <button
              type="submit"
              disabled={checkInMutation.isPending}
              className="w-full py-3 bg-mint-500 hover:bg-mint-400 text-white font-bold text-xs rounded-xl shadow-soft transition-all active:scale-[0.98] disabled:opacity-75 disabled:pointer-events-none flex items-center justify-center gap-1.5"
            >
              {checkInMutation.isPending && <Loader2 className="w-4 h-4 animate-spin" />}
              Confirm My Presence
            </button>
          </form>
        ) : (
          <div className="text-center space-y-6 py-4 animate-scale-in">
            <div className="w-14 h-14 bg-mint-50 border border-mint-100 rounded-2xl flex items-center justify-center text-mint-500 mx-auto">
              <CheckCircle2 className="w-8 h-8" />
            </div>

            <div className="space-y-2">
              <h3 className="text-sm font-bold text-text-primary">Attendance Confirmed!</h3>
              <p className="text-[11px] text-text-secondary leading-relaxed px-4">
                {successData.message}
              </p>
            </div>

            <div className="bg-beige-50/50 p-4 rounded-2xl border border-beige-200 text-xs font-semibold space-y-1.5 max-w-xs mx-auto">
              <div className="flex justify-between">
                <span className="text-text-secondary">Logged Status:</span>
                <span className="text-mint-500 font-extrabold">PRESENT</span>
              </div>
              <div className="flex justify-between">
                <span className="text-text-secondary">Check-in Date:</span>
                <span className="text-text-primary">
                  {new Date(successData.record.createdAt).toLocaleDateString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric'
                  })}
                </span>
              </div>
            </div>

            <button
              onClick={() => router.push(`/dashboard/student/courses/${successData.record.courseId}`)}
              className="px-6 py-2.5 bg-mint-500 hover:bg-mint-400 text-white font-bold text-xs rounded-xl shadow-soft transition-all"
            >
              Go to Course Details
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
